baseURL = 'https://josensosa.com/'
languageCode = 'en-us'
title = 'Jose N Sosa'
alwaysopen = true
[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
[[params.themeVariant]]
    auto = ['zen-light', 'zen-dark']
    identifier = 'zen-auto'
    name = 'Zen Light/Dark'

  [[params.themeVariant]]
    identifier = 'zen-light'

  [[params.themeVariant]]
    identifier = 'zen-dark'

#alwaysopen = true

#collapsibleMenu = true
#params.collapsibleMenu = true

ordersectionsby = 'title'
